# Datasets processing

In [1]:
# Processing procedures of the data we are using 

# Adult Income     https://archive.ics.uci.edu/ml/datasets/adult
# COMPAS           https://www.kaggle.com/datasets/danofer/compass
# Diabetes         https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008
# German Credit    https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data
# HELOC            https://community.fico.com/s/explainable-machine-learning-challenge
# HIGGS            OpenML
# Independent      
# Synthetic        OpenXAI

In [2]:
import time
import numpy as np
import pandas as pd
import zipfile as zf
import nbimporter

import sys

# Adult Income

# COMPAS

# Diabetes

# German Credit

In [6]:
raw_data_ger= pd.read_csv('data/german_credit_data.csv', index_col='ID')

raw_data_ger.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
ID,,,,,,,,,
0,67,male,2,own,NaN,little,1169,6,radio/TV
1,22,female,2,own,little,moderate,5951,48,radio/TV
2,49,male,1,own,little,NaN,2096,12,education
3,45,male,2,free,little,little,7882,42,furniture/equipment
4,53,male,2,free,little,little,4870,24,car

# HELOC

In [5]:
heloc= pd.read_csv('data/heloc_dataset_cleaned.csv')

# split synth into features (x) and target (y)
x_heloc= heloc.loc[:,heloc.columns[1:24]]
y_heloc= heloc.loc[:,heloc.columns[0:1]]

x_heloc.head()

,ExternalRiskEstimate,MSinceOldestTradeOpen,MSinceMostRecentTradeOpen,AverageMInFile,NumSatisfactoryTrades,NumTrades60Ever2DerogPubRec,NumTrades90Ever2DerogPubRec,PercentTradesNeverDelq,MSinceMostRecentDelq,MaxDelq2PublicRecLast12M,...,PercentInstallTrades,MSinceMostRecentInqexcl7days,NumInqLast6M,NumInqLast6Mexcl7days,NetFractionRevolvingBurden,NetFractionInstallBurden,NumRevolvingTradesWBalance,NumInstallTradesWBalance,NumBank2NatlTradesWHighUtilization,PercentTradesWBalance
0,55.0,144.0,4,84,20,3,0,83,2.0,3,...,43,0.0,0,0,33.0,?,8.0,1.0,1.0,69.0
1,61.0,58.0,15,41,2,4,4,100,?,0,...,67,0.0,0,0,0.0,?,0.0,?,?,0.0
2,67.0,66.0,5,24,9,0,0,100,?,7,...,44,0.0,4,4,53.0,66.0,4.0,2.0,1.0,86.0
3,66.0,169.0,1,73,28,1,1,93,76.0,6,...,57,0.0,5,4,72.0,83.0,6.0,4.0,3.0,91.0
4,81.0,333.0,27,132,12,0,0,100,?,7,...,25,0.0,1,1,51.0,89.0,3.0,1.0,0.0,80.0

# HIGGS

In [4]:
ds= zf.ZipFile('data/higgs_98k.zip')

higgs= pd.read_csv(ds.open('higgs_98k.csv'), low_memory=False)

# split synth into features (x) and target (y)
x_higgs= higgs.loc[:,higgs.columns[1:29]]
y_higgs= higgs.loc[:,higgs.columns[0:1]]

x_higgs.head()

,lepton_pT,lepton_eta,lepton_phi,missing_energy_magnitude,missing_energy_phi,jet1pt,jet1eta,jet1phi,jet1b-tag,jet2pt,...,jet4eta,jet4phi,jet4b-tag,m_jj,m_jjj,m_lv,m_jlv,m_bb,m_wbb,m_wwbb
0,0.907542,0.329147,0.359412,1.497970,-0.313010,1.095531,-0.557525,-1.588230,2.173076,0.812581,...,-1.138930,-0.000819110195152462,0,0.302219897508621,0.833048164844513,0.985699653625488,0.978098392486572,0.779732167720795,0.992355763912201,0.79834258556366
1,0.798835,1.470639,-1.635975,0.453773,0.425629,1.104875,1.282322,1.381664,0.000000,0.851737,...,1.128848,0.900460839271545,0,0.909753262996674,1.10833048820496,0.985692203044891,0.951331257820129,0.803251504898071,0.865924417972565,0.780117571353912
2,1.344385,-0.876626,0.935913,1.992050,0.882454,1.786066,-1.646778,-0.942383,0.000000,2.423265,...,-0.678379,-1.36035633087158,0,0.946652472019196,1.0287036895752,0.998656094074249,0.728280603885651,0.869200229644775,1.02673649787903,0.957903981208801
3,1.105009,0.321356,1.522401,0.882808,-1.205349,0.681466,-1.070464,-0.921871,0.000000,0.800872,...,-0.373566,0.113040611147881,0,0.755856454372406,1.36105704307556,0.986609697341919,0.838084638118744,1.13329517841339,0.872244894504547,0.808486521244049
4,1.595839,-0.607811,0.007075,1.818450,-0.111906,0.847550,-0.566437,1.581239,2.173076,0.755421,...,-0.654227,-1.27434492111206,3.10196137428284,0.823760569095612,0.938191413879395,0.971758186817169,0.789176344871521,0.430553287267685,0.961356937885284,0.957817912101746

# Independent

# Synthetic

In [7]:
synth_ox= pd.read_csv('data/synth_OX_20.csv')

# split synth into features (x) and target (y)
df_inputs= synth_ox.loc[:,synth_ox.columns[0:20]]
df_labels= synth_ox.loc[:,synth_ox.columns[20:21]]

df_inputs.head()

,ft_1,ft_2,ft_3,ft_4,ft_5,ft_6,ft_7,ft_8,ft_9,ft_10,ft_11,ft_12,ft_13,ft_14,ft_15,ft_16,ft_17,ft_18,ft_19,ft_20
0,0.325761,0.472693,0.385410,0.312884,0.271236,0.207762,0.620768,0.083032,0.380621,0.385330,0.661285,0.607623,0.369915,0.662277,0.266994,0.327500,0.532432,0.394437,0.340003,0.429918
1,0.391322,0.439526,0.399563,0.394650,0.292309,0.425911,0.405543,0.767337,0.396363,0.373539,0.434264,0.481565,0.244531,0.238732,0.337101,0.624010,0.301257,0.388973,0.563497,0.570738
2,0.381488,0.723214,0.272272,0.415180,0.283829,0.428776,0.359133,0.394703,0.170128,0.264208,0.340062,0.436833,0.357293,0.505398,0.311589,0.651714,0.489318,0.498270,0.449700,0.531800
3,0.306399,0.198559,0.360769,0.301099,0.801582,0.207521,0.348990,0.240065,0.317928,0.134672,0.538223,0.613235,0.373322,0.494310,0.436847,0.372760,0.671813,0.506265,0.534691,0.509233
4,0.298658,0.286087,0.301725,0.460478,0.515515,0.264769,0.375526,0.297023,0.271326,0.711050,0.506832,0.484622,0.405023,0.355244,0.330762,0.502291,0.423997,0.393348,0.255827,0.477407